leahkemp/pipeface

pipeface.nf

Fix reported SV caller when a single SV caller is selected

---

pipeface.nf

Add various user input checks for `in_data.csv` file

Check in data

---

config/nextflow_pipeface.config
pipeface.nf

- Extend checks on user input's for in_data.csv file
- Lighten the disk usage of minimap2 by removing the need for the `samtools addreplacerg` step
- Increase the walltime for the merge_runs process
- Fix bug in reported SV caller when a single SV caller is selected
- Minor changes to code comments

Release v0.1.1

---

README.md
pipeface.nf

Add [whatshap stats](https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-stats)

Whatshap stats

---

README.md
config/nextflow_pipeface.config
config/parameters_pipeface.json
docs/run_on_nci.md
pipeface.nf

Add [pb-CpG-tools](https://github.com/PacificBiosciences/pb-CpG-tools)

pb-CpG-tools

---

README.md
config/nextflow_pipeface.config
config/parameters_pipeface.json
docs/run_on_nci.md
pipeface.nf

- Optimise the DeepVariant stage by splitting it into sub-stages that can run as separate jobs on queues (CPU/GPU) best suited to their computational requirements 
- Use the environment module for DeepVariant

Optimise the DeepVariant stage

---

README.md
config/nextflow_pipeface.config
config/parameters_pipeface.json
docs/run_on_nci.md
pipeface.nf

Changes:
- Optimise DeepVariant thanks to @kisarur!

Release v0.2.1

---

README.md
config/nextflow_pipeface.config
docs/database_versions.txt
docs/run_on_nci.md
pipeface.nf

New features:
- Structural variant annotation (hg38 only)
Other changes:
- Set the minimum length of SV's during variant calling to 50
- Minor changes to documentation

Release v0.3.0

---

config/in_data.csv
docs/run_on_nci.md
pipeface.nf

New features:
- Change output directory structure to align with internal needs and in preparation for adding cohort analysis
Other changes:
- Simplify input/output tuples throughout the pipeline
- Other minor modifications to formatting/syntax/grammar

Release v0.4.0

---

pipeface.nf

Fix clair3 no data_type bug

---

pipeface.nf

Bug fixes:
Fixes https://github.com/leahkemp/pipeface/issues/26

Release v0.4.1

---

NONE
pipeface.nf

Handle creating dummy NONE file for optional pipeface inputs within pipeline which enables running pipeline from remote directories

Handle creating NONE file within pipeline

---

docs/run_on_nci.md
pipeface.nf

- Handle input SV VCF as a pipeline input (secret sauce/undocumented option)
- Minor changes to documentation
- Minor changes to error messages (avoid duplicate printing of the phrase "Error")
- Some re-wording of error messages
- Fix error checks on in_data.csv by passing family_id to channel
- Fix input tuples for vep_sniffles_sv and vep_cutesv_sv proccesses

Input SV VCF

---

NONE
docs/run_on_nci.md
pipeface.nf

New features:
- Handle input SV VCF as a pipeline input (secret sauce/undocumented option)
Other changes:
- Handle creating dummy NONE file for optional pipeface inputs within pipeline which enables running pipeline from remote directories
- Minor changes to formatting of reported in_data format in pipeface_settings.txt files
- Minor changes to documentation
- Minor changes to code comments
- Minor changes to error messages
- Fix input tuples for vep_sniffles_sv and vep_cutesv_sv processes

Release v0.4.2

---

README.md
config/nextflow_pipeface.config
docs/run_on_nci.md
docs/software_versions.txt
pipeface.nf

New features:
- Add minimod
Other changes:
- Minor changes to documentation

Release v0.5.0

---

config/nextflow_pipeface.config
docs/software_versions.txt
pipeface.nf

- Extend minimod - generate bigwig file
- Also report a few software in `docs/software_versions.txt` which have been missed

Minimod extend

---

README.md
config/nextflow_pipeface.config
docs/software_versions.txt
pipeface.nf

Split multiallelic variants into biallelic variants

Multiallelic sites

---

pipeface.nf

- Make minimod haplotype aware

Minimod haplotype aware

---

docs/software_versions.txt
pipeface.nf

- Update SV caller (sniffles and cuteSV) versions

Update SV callers

---

pipeface.nf

Remove calling of SV's in regions of interest only

---

pipeface.nf

Bug fixes:
- Remove calling of SV's in regions of interest only. Fixes #45

Release 0.6.2

---

pipeface.nf

Add zero genotypes in jasmine as default

Jasmine zero genotypes

---

README.md

Add info on how to collaboratively code

Add info on how to collaboratively code

---

pipeface.nf

Add platform specific settings for jasmine

Add platform specific settings for jasmine

---

config/nextflow_pipeface.config
pipeface.nf

Update DeepVariant/DeepTrio to v1.8.0

DeepVariant/DeepTrio Update

---

pipeface.nf

Tag pipeface version in pipeface_settings.txt files

Tag pipeface version

---

README.md
config/nextflow_pipeface.config
config/parameters_pipeface.json
docs/run_on_nci.md
docs/software_versions.txt
pipeface.nf

New features:
- Add somalier
Other changes:
- DeepVariant/DeepTrio Update (version 1.6.1 to version 1.8.0) thanks to @kisarur !. This means even more speed increases and in turn cost reductions!
- Tag pipeface version in pipeface_settings.txt files (thanks to the feedback from Edward Formaini @EddieLF !)
- Update samtools, htslib, minimod, bcftools
- Add un-reported bedtools in the software_versions.txt file
- Organising of `nextflow_pipeface.config` file

Release 0.8.0

---

pipeface.nf

Drop writing of per base file and in turn speed up mosdepth

Speed up mosdepth

---

pipeface.nf

- Include all variants in annotated VCF irrespective of their VEP support
- Convert TRA variants back to BND variants directly after jasmine

Include all vars in annotated VCF and convert TRA to BND

---

config/nextflow_pipeface.config
pipeface.nf

Reference filling for joint SV VCF's

Ref filling

---

pipeface.nf

Bug fixes:
- Drop ref filling for now. Fixes #73

Release 0.9.1

---

pipeface.nf

Add extra error checks. Fixes #78 .

Add extra error checks

---

pipeface.nf

- Improvements to the VEP annotation
- Intergenic or intronic consequences are prioritised over upstream/downstream variants. As well as higher-impact consequences such as missense, splice variants and frameshift.

VEP tweaks
